/// Таксономия жанров: у трека ОДИН основной жанр (несовместимые не смешиваются).
/// Категории (настроение/контекст) при этом могут комбинироваться.
class GenreTaxonomy {
  static const List<String> all = [
    'Rock',
    'Pop',
    'Hip-Hop',
    'Electronic',
    'Dance',
    'Jazz',
    'Classical',
    'Metal',
    'Punk',
    'Alternative',
    'Indie',
    'R&B',
    'Soul',
    'Funk',
    'Blues',
    'Country',
    'Folk',
    'Latin',
    'Reggae',
    'K-Pop',
    'Ambient',
    'Lo-Fi',
    'Phonk',
    'Synthwave',
    'House',
    'Techno',
    'Drum & Bass',
    'Dubstep',
    'Trap',
    'Soundtrack',
    'Chanson',
    'Estrada',
  ];

  /// Нормализация онлайн-жанров (iTunes primaryGenreName) в таксономию.
  /// null = неизвестно, не кэшируем как жанр.
  static String? normalizeOnline(String raw) {
    final g = raw.trim().toLowerCase();
    const map = {
      'rock': 'Rock',
      'alternative': 'Alternative',
      'indie': 'Indie',
      'pop': 'Pop',
      'vocal': 'Pop',
      'pop/rock': 'Rock',
      'hip-hop': 'Hip-Hop',
      'hip-hop/rap': 'Hip-Hop',
      'rap': 'Hip-Hop',
      'r&b': 'R&B',
      'r&b/soul': 'R&B',
      'soul': 'Soul',
      'funk': 'Funk',
      'blues': 'Blues',
      'country': 'Country',
      'folk': 'Folk',
      'singer/songwriter': 'Folk',
      'latin': 'Latin',
      'latino': 'Latin',
      'reggae': 'Reggae',
      'reggaeton': 'Latin',
      'k-pop': 'K-Pop',
      'j-pop': 'Pop',
      'japanese': 'K-Pop',
      'korean': 'K-Pop',
      'electronic': 'Electronic',
      'dance': 'Dance',
      'house': 'House',
      'techno': 'Techno',
      'trance': 'Electronic',
      'dubstep': 'Dubstep',
      'drum & bass': 'Drum & Bass',
      "drum'n'bass": 'Drum & Bass',
      'dnb': 'Drum & Bass',
      'trap': 'Trap',
      'phonk': 'Phonk',
      'synthwave': 'Synthwave',
      'synthpop': 'Synthwave',
      'lo-fi': 'Lo-Fi',
      'lofi': 'Lo-Fi',
      'ambient': 'Ambient',
      'new age': 'Ambient',
      'jazz': 'Jazz',
      'classical': 'Classical',
      'opera': 'Classical',
      'metal': 'Metal',
      'punk': 'Punk',
      'hard rock': 'Rock',
      'soundtrack': 'Soundtrack',
      'soundtracks': 'Soundtrack',
      'chanson': 'Chanson',
      'shanson': 'Chanson',
      'шансон': 'Chanson',
      'estrada': 'Estrada',
      'эстрада': 'Estrada',
      'попса': 'Estrada',
    };
    if (map.containsKey(g)) return map[g];
    for (final t in all) {
      if (g.contains(t.toLowerCase())) return t;
    }
    return null;
  }

  /// Ключевые слова (название+исполнитель+альбом) -> жанр. RU+EN.
  static const Map<String, List<String>> keywords = {
    'Rock': [
      'rock',
      'рок',
      'ac/dc',
      'queen',
      'nirvana',
      'rhapsody',
      'guitar',
      'гитара',
    ],
    'Metal': [
      'metal',
      'метал',
      'rammstein',
      'slipknot',
      'iron maiden',
      'death',
      'black metal',
      'doom',
    ],
    'Punk': [
      'punk',
      'панк',
      'sex pistols',
      'ramones',
      'offspring',
      'green day',
    ],
    'Hip-Hop': [
      'hip-hop',
      'hip hop',
      'rap',
      'рэп',
      'хип-хоп',
      'eminem',
      'drake',
      'kendrick',
      'travis scott',
      'oxxxymiron',
      'оксимирон',
      'basta',
      'баста',
      'morgenshtern',
      'моргенштерн',
    ],
    'Pop': [
      'pop',
      'поп',
      'madonna',
      'taylor swift',
      'dua lipa',
      'ариана',
      'bts',
      'one direction',
    ],
    'Electronic': [
      'electronic',
      'электрон',
      'depeche mode',
      'kraftwerk',
      'synth',
      'синт',
      'edm',
      'avicii',
    ],
    'Dance': ['dance', 'танцевальн', 'eurodance', 'hands up', 'cascada'],
    'House': [
      'house',
      'хаус',
      'deep house',
      'david guetta',
      'calvin harris',
      'fisher',
    ],
    'Techno': [
      'techno',
      'техно',
      'charlotte de witte',
      'amelie lens',
      'boris brejcha',
    ],
    'Drum & Bass': [
      'drum and bass',
      'drum & bass',
      'dnb',
      'драм',
      'pendulum',
      'netsky',
      'sub focus',
    ],
    'Dubstep': ['dubstep', 'дабстеп', 'skrillex', 'excision'],
    'Trap': ['trap', 'трэп', 'future ', 'metro boomin'],
    'Phonk': ['phonk', 'фонк', 'drift phonk', 'ghostface playa', 'kaito shoma'],
    'Synthwave': [
      'synthwave',
      'синтвейв',
      'retrowave',
      'outrun',
      'kavinsky',
      'gunship',
      'carpenter brut',
    ],
    'Lo-Fi': [
      'lo-fi',
      'lofi',
      'лофай',
      'chillhop',
      'lofi hip hop',
      'jinsang',
      'nujabes',
    ],
    'Ambient': [
      'ambient',
      'эмбиент',
      'brian eno',
      'stars of the lid',
      'meditation',
      'медитац',
    ],
    'Jazz': [
      'jazz',
      'джаз',
      'miles davis',
      'coltrane',
      'sinatra',
      'ella fitzgerald',
      'bossa nova',
      'босса',
    ],
    'Classical': [
      'classical',
      'классика',
      'mozart',
      'beethoven',
      'bach',
      'vivaIdi',
      'symphony',
      'симфони',
      'orchestra',
      'оркестр',
      'piano concerto',
    ],
    'Blues': ['blues', 'блюз', 'b.b. king', 'muddy waters'],
    'Country': ['country', 'кантри', 'johnny cash', 'dolly parton'],
    'Folk': [
      'folk',
      'фолк',
      'singer-songwriter',
      'бард',
      'высоцкий',
      'окуджава',
    ],
    'Latin': [
      'latin',
      'латино',
      'reggaeton',
      'реггетон',
      'salsa',
      'сальса',
      'despacito',
      'shakira',
      'bad bunny',
    ],
    'Reggae': ['reggae', 'регги', 'bob marley', 'marley'],
    'R&B': ['r&b', 'rnb', 'the weeknd', 'sza', 'usher', 'alicia keys'],
    'Soul': ['soul', 'соул', 'aretha', 'marvin gaye', 'sam cooke'],
    'Funk': ['funk', 'фанк', 'james brown', 'parliament'],
    'K-Pop': [
      'k-pop',
      'kpop',
      'кей-поп',
      'bts',
      'blackpink',
      'stray kids',
      'twice',
      'exo',
    ],
    'Soundtrack': [
      'soundtrack',
      'саундтрек',
      'ost ',
      'score',
      'hans zimmer',
      'anime',
      'аниме',
      'amv',
    ],
    'Alternative': [
      'alternative',
      'альтернатив',
      'radiohead',
      'arctic monkeys',
      'placebo',
      'muse',
    ],
    'Indie': [
      'indie',
      'инди',
      'tame impala',
      'arctic monkeys',
      'the strokes',
      'vampire weekend',
    ],
    'Chanson': ['chanson', 'шансон', 'круг', 'михаил круг', 'лепс'],
    'Estrada': [
      'эстрада',
      'пугачева',
      'киркоров',
      'басков',
      'аллегрова',
      'леонтьев',
    ],
  };

  static String guessFromText(String text) {
    final t = text.toLowerCase();
    String? best;
    int bestLen = 0;
    keywords.forEach((genre, kws) {
      for (final k in kws) {
        if (k.length >= bestLen && t.contains(k)) {
          // более длинные совпадения точнее коротких
          if (k.length > bestLen) {
            best = genre;
            bestLen = k.length;
          }
        }
      }
    });
    return best ?? 'Прочее';
  }
}
